# Generated by Django 5.0.dev20230308105257 on 2023-04-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default='', upload_to='carregar/'),
        ),
    ]
